include_guard()

set(BIG_PLATFORM ${CMAKE_SYSTEM_NAME})

if(${BIG_PLATFORM} STREQUAL "Windows")
    set(BIG_PLATFORM_WINDOWS 1)
elseif(${BIG_PLATFORM} STREQUAL "Linux")
    set(BIG_PLATFORM_LINUX 1)
endif()

set(BIG_WM_X11 1)
#set(BIG_WM_WAYLAND 1)

set(BIG_RENDERER_GL 1)
#set(BIG_RENDERER_VULKAN 1)

if(${BIG_WM_X11})
    set(BIG_COMPILE_DEFS
        SDL_VIDEO_DRIVER_X11=1
    )
else()
    set(BIG_COMPILE_DEFS
        SDL_VIDEO_DRIVER_WAYLAND=1
    )
endif()

if(${BIG_RENDERER_GL})
    set(BIG_COMPILE_DEFS ${BIG_COMPILE_DEFS}
        BGFX_CONFIG_RENDERER_OPENGL=1
        BGFX_CONFIG_RENDERER_OPENGLES=0
        BGFX_CONFIG_RENDERER_VULKAN=0
    )
else()
    set(BIG_COMPILE_DEFS ${BIG_COMPILE_DEFS}
        BGFX_CONFIG_RENDERER_OPENGL=0
        BGFX_CONFIG_RENDERER_OPENGLES=0
        BGFX_CONFIG_RENDERER_VULKAN=1
    )
endif()

set(BIG_ROOT ${CMAKE_CURRENT_LIST_DIR}/..)
set(BX_ROOT ${BIG_ROOT}/lib/bx)
set(BIMG_ROOT ${BIG_ROOT}/lib/bimg)
set(BGFX_ROOT ${BIG_ROOT}/lib/bgfx)
set(IMGUI_ROOT ${BIG_ROOT}/lib/imgui)

#TODO:PRIxPTR???
if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
set(BGFX_COMPATIBILITY ${BX_ROOT}/include/compat/msvc)
endif()
